CREATE TABLE "REG"."LOC_HIERARCHY_LIST"("HIERARCHY_LEVEL" INTEGER NOT NULL, "HIERARCHY_LEVEL_NAME" VARCHAR(36) NOT NULL, "LANG_CODE" VARCHAR(3) NOT NULL, "IS_ACTIVE" BOOLEAN NOT NULL, "CR_BY" VARCHAR(256) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(256), "UPD_DTIMES" TIMESTAMP);

ALTER TABLE "REG"."LOC_HIERARCHY_LIST" ADD CONSTRAINT "PK_LOCHL_ID" PRIMARY KEY ("HIERARCHY_LEVEL", "HIERARCHY_LEVEL_NAME", "LANG_CODE" );

ALTER TABLE "REG"."REGISTRATION" ADD "APP_ID" VARCHAR(39) NOT NULL;
ALTER TABLE "REG"."REGISTRATION_TRANSACTION" ADD "APP_ID" VARCHAR(39) NOT NULL;

CREATE TABLE "REG"."PERMITTED_LOCAL_CONFIG" ("CODE" VARCHAR(128) NOT NULL, "NAME" VARCHAR(128) NOT NULL, "CONFIG_TYPE" VARCHAR(128) NOT NULL, "IS_ACTIVE" BOOLEAN NOT NULL, "CR_BY" VARCHAR(32) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(32), "UPD_DTIMES" TIMESTAMP, "IS_DELETED" BOOLEAN, "DEL_DTIMES" TIMESTAMP);

ALTER TABLE "REG"."PERMITTED_LOCAL_CONFIG" ADD CONSTRAINT "PK_PERMCONFIG_CODE" PRIMARY KEY ("CODE");

CREATE TABLE "REG"."LOCAL_PREFERENCES" ("ID" VARCHAR(36) NOT NULL, "NAME" VARCHAR(128) NOT NULL, "VAL" VARCHAR(512), "CONFIG_TYPE" VARCHAR(128) NOT NULL, "MACHINE_NAME" VARCHAR(128) NOT NULL,"CR_BY" VARCHAR(32) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(32), "UPD_DTIMES" TIMESTAMP, "IS_DELETED" BOOLEAN, "DEL_DTIMES" TIMESTAMP);

ALTER TABLE "REG"."LOCAL_PREFERENCES" ADD CONSTRAINT "PK_LOCPREF_ID" PRIMARY KEY ("ID");
