----- create new tables

CREATE TABLE "REG"."LOC_HIERARCHY_LIST"("HIERARCHY_LEVEL" INTEGER NOT NULL, "HIERARCHY_LEVEL_NAME" VARCHAR(36) NOT NULL, "LANG_CODE" VARCHAR(3) NOT NULL, "IS_ACTIVE" BOOLEAN NOT NULL, "CR_BY" VARCHAR(256) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(256), "UPD_DTIMES" TIMESTAMP);
ALTER TABLE "REG"."LOC_HIERARCHY_LIST" ADD CONSTRAINT "PK_LOCHL_ID" PRIMARY KEY ("HIERARCHY_LEVEL", "HIERARCHY_LEVEL_NAME", "LANG_CODE" );

CREATE TABLE "REG"."PERMITTED_LOCAL_CONFIG" ("CODE" VARCHAR(128) NOT NULL, "NAME" VARCHAR(128) NOT NULL, "CONFIG_TYPE" VARCHAR(128) NOT NULL, "IS_ACTIVE" BOOLEAN NOT NULL, "CR_BY" VARCHAR(32) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(32), "UPD_DTIMES" TIMESTAMP, "IS_DELETED" BOOLEAN, "DEL_DTIMES" TIMESTAMP);
ALTER TABLE "REG"."PERMITTED_LOCAL_CONFIG" ADD CONSTRAINT "PK_PERMCONFIG_CODE" PRIMARY KEY ("CODE");

CREATE TABLE "REG"."LOCAL_PREFERENCES" ("ID" VARCHAR(36) NOT NULL, "NAME" VARCHAR(128) NOT NULL, "VAL" VARCHAR(512), "CONFIG_TYPE" VARCHAR(128) NOT NULL, "MACHINE_NAME" VARCHAR(128) NOT NULL,"CR_BY" VARCHAR(32) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(32), "UPD_DTIMES" TIMESTAMP, "IS_DELETED" BOOLEAN, "DEL_DTIMES" TIMESTAMP);
ALTER TABLE "REG"."LOCAL_PREFERENCES" ADD CONSTRAINT "PK_LOCPREF_ID" PRIMARY KEY ("ID");

CREATE TABLE "REG"."PROCESS_SPEC" ("ID" VARCHAR(100) NOT NULL, "TYPE" VARCHAR(100) NOT NULL, "ID_VERSION" VARCHAR(8), "ORDER_NUM" INTEGER NOT NULL, "IS_SUB_PROCESS" BOOLEAN  NOT NULL, "FLOW" VARCHAR(36) NOT NULL, "IS_ACTIVE" BOOLEAN NOT NULL);
ALTER TABLE "REG"."PROCESS_SPEC" ADD CONSTRAINT "PK_PROCSPEC_TYPE" PRIMARY KEY ("TYPE");
ALTER TABLE "REG"."PROCESS_SPEC" ADD CONSTRAINT "UK_PROCSPEC_ID" UNIQUE ("ID");

CREATE TABLE "REG"."FILE_SIGNATURE" ("FILE_NAME" VARCHAR(100) NOT NULL, "SIGNATURE" VARCHAR(2048) NOT NULL, "CONTENT_LENGTH" BIGINT, "ENCRYPTED" BOOLEAN  NOT NULL);

----- drop unwanted tables & constraint

DROP TABLE IF EXISTS "REG"."AUDIT_LOG_CONTROL" CASCADE;
DROP CONSTRAINT IF EXISTS "FK_ALGC_REG";
DROP CONSTRAINT IF EXISTS "PK_ALGC";

DROP TABLE IF EXISTS "REG"."DEVICE_TYPE" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_DTYP_CODE";

DROP TABLE IF EXISTS "REG"."REG_CENTER_MACHINE_DEVICE" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_CNTRMDEV_CNTR_ID";

DROP TABLE IF EXISTS "REG"."MOSIP_DEVICE_SERVICE" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_MDS_ID";
DROP CONSTRAINT IF EXISTS "UK_MDS";

DROP TABLE IF EXISTS "REG"."REG_CENTER_MACHINE" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_CNTRMAC_USR_ID";

DROP TABLE IF EXISTS "REG"."GENDER" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_GNDR_CODE";

DROP TABLE IF EXISTS "REG"."GENDER" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_GNDR_CODE";

DROP TABLE IF EXISTS "REG"."FOUNDATIONAL_TRUST_PROVIDER" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_FTPRD_ID";

DROP TABLE IF EXISTS "REG"."INDIVIDUAL_TYPE" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_INDVTYP_CODE";

DROP TABLE IF EXISTS "REG"."DEVICE_SPEC" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_DSPEC_CODE";

DROP TABLE IF EXISTS "REG"."DEVICE_MASTER" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_DEVICEM_ID";

DROP TABLE IF EXISTS "REG"."REG_DEVICE_SUB_TYPE" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_RDSTYP_CODE";
DROP CONSTRAINT IF EXISTS "UK_RDSTYP";

DROP TABLE IF EXISTS "REG"."REG_CENTER_DEVICE" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_CNTRDEV_ID";

DROP TABLE IF EXISTS "REG"."TITLE" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_TTL_CODE";

DROP TABLE IF EXISTS "REG"."APP_DETAIL" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_APPDTL_ID";
DROP INDEX "REG"."IDX_APPDTL_NAME" ON "REG"."APP_DETAIL";

DROP TABLE IF EXISTS "REG"."REG_DEVICE_TYPE" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_RDTYP_CODE";

DROP TABLE IF EXISTS "REG"."DEVICE_PROVIDER" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_DEVPRD_ID";

DROP TABLE IF EXISTS "REG"."TEMPLATE_TYPE" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_TMPLTYP_CODE";

DROP TABLE IF EXISTS "REG"."TEMPLATE_FILE_FORMAT" CASCADE;
DROP CONSTRAINT IF EXISTS "PK_TFFMT_CODE";

----- modify columns type & constraint

DROP CONSTRAINT IF EXISTS "PK_MSPEC_CODE";
ALTER TABLE "REG"."MACHINE_SPEC" ADD CONSTRAINT "PK_MSPEC_CODE" PRIMARY KEY ("ID");

DROP CONSTRAINT IF EXISTS "PK_MTYP_CODE";
ALTER TABLE "REG"."MACHINE_TYPE" ADD CONSTRAINT "PK_MTYP_CODE" PRIMARY KEY ("CODE");

DROP CONSTRAINT IF EXISTS "PK_MACHM_ID";
ALTER TABLE "REG"."MACHINE_MASTER" ADD CONSTRAINT "PK_MACHM_ID" PRIMARY KEY ("ID");

ALTER TABLE "REG"."MACHINE_SPEC" ALTER COLUMN "LANG_CODE" NULL;
ALTER TABLE "REG"."REG_CENTER_MACHINE" ALTER COLUMN "LANG_CODE" NULL;
ALTER TABLE "REG"."USER_DETAIL" ALTER COLUMN "STATUS_CODE" NULL;
ALTER TABLE "REG"."TEMPLATE_TYPE" ALTER COLUMN "LANG_CODE" NULL;
ALTER TABLE "REG"."VALID_DOCUMENT" ALTER COLUMN "LANG_CODE" NULL;
ALTER TABLE "REG"."MACHINE_MASTER" ALTER COLUMN "LANG_CODE" NULL;
ALTER TABLE "REG"."MACHINE_MASTER" ALTER COLUMN "MAC_ADDRESS" NULL;
ALTER TABLE "REG"."MACHINE_MASTER" ALTER COLUMN "SERIAL_NUM" NULL;
ALTER TABLE "REG"."MACHINE_MASTER" ALTER COLUMN "PUBLIC_KEY" NOT NULL;
ALTER TABLE "REG"."MACHINE_MASTER" ALTER COLUMN "KEY_INDEX" NOT NULL;
ALTER TABLE "REG"."TEMPLATE_FILE_FORMAT" ALTER COLUMN "LANG_CODE" NULL;
ALTER TABLE "REG"."MACHINE_TYPE" ALTER COLUMN "LANG_CODE" NULL;

ALTER TABLE "REG"."CA_CERT_STORE" ADD CONSTRAINT "UK_CERT_THUMBPRINT" UNIQUE ("CERT_THUMBPRINT", "PARTNER_DOMAIN");

----- Changes in registration and its related tables

DROP CONSTRAINT IF EXISTS "PK_REG_ID";
ALTER TABLE "REG"."REGISTRATION" ADD COLUMN "APP_ID" VARCHAR(39) NOT NULL;
ALTER TABLE "REG"."REGISTRATION" ADD COLUMN "PACKET_ID" VARCHAR(256) NOT NULL;
ALTER TABLE "REG"."REGISTRATION" ADD COLUMN "ADDITIONAL_INFO_REQ_ID" VARCHAR(128);
ALTER TABLE "REG"."REGISTRATION" ADD COLUMN "ACK_SIGNATURE" VARCHAR(350);
ALTER TABLE "REG"."REGISTRATION" ADD COLUMN "HAS_BWORDS" BOOLEAN;
UPDATE "REG"."REGISTRATION" SET PACKET_ID=ID;
ALTER TABLE "REG"."REGISTRATION" ADD CONSTRAINT "PK_REG_ID" PRIMARY KEY ("PACKET_ID");

ALTER TABLE "REG"."REGISTRATION_TRANSACTION" ADD COLUMN "APP_ID" VARCHAR(39) NOT NULL;

----- insert / update statements

UPDATE "REG"."GLOBAL_PARAM" set VAL='DEVICE' WHERE CODE='mosip.registration.mdm.trust.domain.digitalId';
INSERT INTO "REG"."GLOBAL_PARAM" VALUES ('mosip.kernel.vid.restricted-numbers','mosip.kernel.vid.restricted-numbers','786,666','CONFIGURATION','eng',true,'SYSTEM',current timestamp, 'SYSTEM',current timestamp, false, current timestamp);
INSERT INTO "REG"."GLOBAL_PARAM" VALUES ('mosip.kernel.vid.not-start-with','mosip.kernel.vid.not-start-with','0,1','CONFIGURATION','eng',true,'SYSTEM',current timestamp, 'SYSTEM',current timestamp, false, current timestamp);
INSERT INTO "REG"."GLOBAL_PARAM" VALUES ('mosip.kernel.vid.length.repeating-limit','mosip.kernel.vid.length.repeating-limit','2','CONFIGURATION','eng',true,'SYSTEM',current timestamp, 'SYSTEM',current timestamp, false, current timestamp);
INSERT INTO "REG"."GLOBAL_PARAM" VALUES ('mosip.kernel.vid.length.repeating-block-limit','mosip.kernel.vid.length.repeating-block-limit','2','CONFIGURATION','eng',true,'SYSTEM',current timestamp, 'SYSTEM',current timestamp, false, current timestamp);
INSERT INTO "REG"."GLOBAL_PARAM" VALUES ('mosip.kernel.vid.length.sequence-limit','mosip.kernel.vid.length.sequence-limit','3','CONFIGURATION','eng',true,'SYSTEM',current timestamp, 'SYSTEM',current timestamp, false, current timestamp);
INSERT INTO "REG"."GLOBAL_PARAM" VALUES ('mosip.kernel.vid.length','mosip.kernel.vid.length','16','CONFIGURATION','eng',true,'SYSTEM',current timestamp, 'SYSTEM',current timestamp, false, current timestamp);
INSERT INTO "REG"."GLOBAL_PARAM" VALUES ('mosip.registration.audit_timestamp','mosip.registration.audit_timestamp',current timestamp,'CONFIGURATION','eng',true,'SYSTEM',current timestamp, 'SYSTEM',current timestamp, false, current timestamp);