DROP TABLE IF EXISTS reg.LOC_HIERARCHY_LIST CASCADE;
DROP CONSTRAINT IF EXISTS PK_LOCHL_ID;

DROP TABLE IF EXISTS reg.PERMITTED_LOCAL_CONFIG CASCADE;
DROP CONSTRAINT IF EXISTS PK_PERMCONFIG_CODE;

DROP TABLE IF EXISTS reg.LOCAL_PREFERENCES CASCADE;
DROP CONSTRAINT IF EXISTS PK_LOCPREF_ID;