ALTER TABLE reg.sync_job_def ADD COLUMN "JOB_TYPE" VARCHAR(128);

ALTER TABLE reg.template ADD COLUMN "FILE_TXT_n" CLOB;
UPDATE reg.template SET FILE_TXT_n=FILE_TXT;
ALTER TABLE reg.template DROP COLUMN FILE_TXT;
RENAME COLUMN reg.template.FILE_TXT_n TO FILE_TXT;

ALTER TABLE reg.dynamic_field ADD COLUMN "VALUE_JSON_n" CLOB;
UPDATE reg.dynamic_field SET VALUE_JSON_n=VALUE_JSON;
ALTER TABLE reg.dynamic_field DROP COLUMN VALUE_JSON;
RENAME COLUMN reg.dynamic_field.VALUE_JSON_n TO VALUE_JSON;